### ISSUE TITLE
Readiness for production

### ISSUE THREAD

**Issue by nigel-dewar** [mrochon/RedisTokenCache#1]
Hi There, thanks for providing this.

You mentioned, "not for production use"

Is there any specific things that would be needed to make this "production ready"

It looks good to go to me.

Cheers

**Comment by mrochon** [comment]
No, no specific things that I am aware of. It was just never tested or reviewed with necessary stringency. Enjoy!

Marius

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nigel-dewar** [comment]
Cool, thanks for this. Cheers.
